<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\Department;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $hr = Department::firstOrCreate(['name' => 'الموارد البشرية']);
        $finance = Department::firstOrCreate(['name' => 'المالية']);
        $it = Department::firstOrCreate(['name' => 'تقنية المعلومات']);

        $employees = [
            [
                'name' => 'أحمد محمد',
                'email' => 'ahmed@example.com',
                'phone' => '0912345678',
                'position' => 'موارد بشرية',
                'department_id' => $hr->id,
                'hire_date' => '2022-01-15',
                'cv' => 'storage/cv/ahmed.pdf',
                'profile_photo' => 'storage/photos/ahmed.jpg',
                'address' => 'الخرطوم - بحري',
                'attendance_days' => 200,
                'absence_days' => 5,
                'late_arrivals' => 3,
                'early_leaves' => 2,
                'leave_count' => 1,
                'leave_duration' => 10,
                'leave_type' => 'official',
                'leave_paid' => true,
                'salary' => 50000,
                'bonus' => 5000,
                'advance' => 2000,
                'discipline_rate' => 95,
                'notes' => 'موظف ملتزم بشكل عام',
                'status' => 'active',
                'warnings' => 0,
            ],
            [
                'name' => 'سارة علي',
                'email' => 'sara@example.com',
                'phone' => '0998765432',
                'position' => 'محاسبة',
                'department_id' => $finance->id,
                'hire_date' => '2023-03-01',
                'cv' => 'storage/cv/sara.pdf',
                'profile_photo' => 'storage/photos/sara.jpg',
                'address' => 'أم درمان - الثورة',
                'attendance_days' => 150,
                'absence_days' => 10,
                'late_arrivals' => 5,
                'early_leaves' => 1,
                'leave_count' => 2,
                'leave_duration' => 8,
                'leave_type' => 'sick',
                'leave_paid' => false,
                'salary' => 45000,
                'bonus' => 3000,
                'advance' => 1000,
                'discipline_rate' => 88,
                'notes' => 'تحتاج متابعة في الحضور',
                'status' => 'terminated',
                'warnings' => 1,
            ],
            [
                'name' => 'سعد علي',
                'email' => 'saad@example.com',
                'phone' => '0934567890',
                'position' => 'مشرف',
                'department_id' => $hr->id,
                'hire_date' => '2021-07-10',
                'cv' => 'storage/cv/saad.pdf',
                'profile_photo' => 'storage/photos/saad.jpg',
                'address' => 'الخرطوم - الصحافة',
                'attendance_days' => 180,
                'absence_days' => 12,
                'late_arrivals' => 7,
                'early_leaves' => 3,
                'leave_count' => 1,
                'leave_duration' => 9,
                'leave_type' => 'official',
                'leave_paid' => true,
                'salary' => 47000,
                'bonus' => 2000,
                'advance' => 1500,
                'discipline_rate' => 80,
                'notes' => 'لديه إنذار بسبب التأخير',
                'status' => 'warning',
                'warnings' => 2,
            ],
            [
                'name' => 'منى حسن',
                'email' => 'mona@example.com',
                'phone' => '0945678901',
                'position' => 'مطور برمجيات',
                'department_id' => $it->id,
                'hire_date' => '2020-05-20',
                'cv' => 'storage/cv/mona.pdf',
                'profile_photo' => 'storage/photos/mona.jpg',
                'address' => 'بحري - الكدرو',
                'attendance_days' => 220,
                'absence_days' => 2,
                'late_arrivals' => 1,
                'early_leaves' => 0,
                'leave_count' => 3,
                'leave_duration' => 12,
                'leave_type' => 'official',
                'leave_paid' => true,
                'salary' => 60000,
                'bonus' => 7000,
                'advance' => 2500,
                'discipline_rate' => 98,
                'notes' => 'متميزة في عملها',
                'status' => 'active',
                'warnings' => 0,
            ],
            [
                'name' => 'خالد عمر',
                'email' => 'khalid@example.com',
                'phone' => '0956789012',
                'position' => 'مسؤول شبكات',
                'department_id' => $it->id,
                'hire_date' => '2019-11-01',
                'cv' => 'storage/cv/khalid.pdf',
                'profile_photo' => 'storage/photos/khalid.jpg',
                'address' => 'أم درمان - المهندسين',
                'attendance_days' => 160,
                'absence_days' => 15,
                'late_arrivals' => 10,
                'early_leaves' => 4,
                'leave_count' => 2,
                'leave_duration' => 7,
                'leave_type' => 'sick',
                'leave_paid' => false,
                'salary' => 55000,
                'bonus' => 4000,
                'advance' => 3000,
                'discipline_rate' => 75,
                'notes' => 'لديه إنذار بسبب مخالفة تعليمات الأمان',
                'status' => 'warning',
                'warnings' => 3,
            ],
        ];

        foreach ($employees as $emp) {
            Employee::firstOrCreate(['email' => $emp['email']], $emp);
        }
    }
}